
spring:
  application:
    name: ms-eureka-server
  profiles:
    active: "prod"
---
server:
  port: ${PORT:8761}
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      enabled: false
  security:
    user:
      name: admin
      password: pwd
eureka:
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
  instance:
    hostname: localhost
    statusPageUrlPath: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrlPath: http://${eureka.instance.hostname}:${server.port}/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:https://radiant-plateau-86737.herokuapp.com/
  cloud:
    config:
      uri: optional:configserver:https://radiant-plateau-86737.herokuapp.com/